#~/.bash_aliases

if [ "$TERM" != "dumb" ]; then
    alias ls='ls -AFG'
fi

alias Preview='open -a Preview'
alias VLC='open -a VLC'
alias 0xED='open -a 0xED'
alias TextEdit='open -a TextEdit'
alias Firefox='open -a Firefox'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias diff='diff -u'
#alias gcc='gcc -ansi -g -Wall'
alias grep='grep --color'
alias mytop='top -o cpu -O rsize'
alias topCPU='top -o cpu'
alias topRM='top -o rsize'
alias topVM='top -o vsize'

alias su='su -l'

