#~/.bash_aliases

alias ls='ls -Ah --color=auto'
#alias ls='ls -ACF --color'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias diff='diff -u'
#alias gcc='gcc -ansi -g -Wall'
alias grep='grep --color'
#alias mytop='top -o cpu -O rsize'
#alias topCPU='top -o cpu'
#alias topRM='top -o rsize'
#alias topVM='top -o vsize'

alias mplayer_tiny='mplayer -lavdopts lowres=1'
#alias mplayer_slow='mplayer -lavdopts lowres=1:fast:skiploopfilter=all'
#alias mplayer_slow='mplayer -vfm ffmpeg -lavdopts lowres=1:fast:skiploopfilter=all'
alias mplayer_zoom='mplayer -zoom'
#alias mplayer_zoom='mplayer -zoom'
#alias eclipse='/opt/eclipse/eclipse'
alias tilda_conf='tilda -C'

alias pstree='pstree -ca'
alias su='su -l'

